version: "3"

services:
  zookeeper1:
    image: zookeeper
    hostname: zookeeper1
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm136]
  zookeeper2:
    image: zookeeper
    hostname: zookeeper2
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm137]
  zookeeper3:
    image: zookeeper
    hostname: zookeeper3
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm138]

  nifi1:
    image: mkobit/nifi:1.1.0-oracle-java8
    hostname: nifi1
    ports:
      - 8080:8080
    user: root
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    volumes:
      - /root/nifi.cluster.docker.swarm/nifi1/nifi.properties:/opt/nifi/conf/nifi.properties:ro
      - /root/nifi.cluster.docker.swarm/nifi1/bootstrap.conf:/opt/nifi/conf/bootstrap.conf:ro
      - /srv/nifi/flow:/opt/nifi/flow:Z
      - /srv/nifi/content_repository:/opt/nifi/content_repository:Z
      - /srv/nifi/database_repository:/opt/nifi/database_repository:Z
      - /srv/nifi/flowfile_repository:/opt/nifi/flowfile_repository:Z
      - /srv/nifi/provenance_repository:/opt/nifi/provenance_repository:Z
      - /srv/nifi/work:/opt/nifi/work:Z
      - /srv/nifi/logs:/opt/nifi/logs:Z
      - /tmp/data:/tmp/data:Z
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm136]
  nifi2:
    image: mkobit/nifi:1.1.0-oracle-java8
    hostname: nifi2
    ports:
      - 8085:8085
    user: root
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=7000,server=y,suspend=n
    volumes:
      - /root/nifi.cluster.docker.swarm/nifi2/nifi.properties:/opt/nifi/conf/nifi.properties:ro
      - /root/nifi.cluster.docker.swarm/nifi2/bootstrap.conf:/opt/nifi/conf/bootstrap.conf:ro
      - /srv/nifi/flow:/opt/nifi/flow:Z
      - /srv/nifi/content_repository:/opt/nifi/content_repository:Z
      - /srv/nifi/database_repository:/opt/nifi/database_repository:Z
      - /srv/nifi/flowfile_repository:/opt/nifi/flowfile_repository:Z
      - /srv/nifi/provenance_repository:/opt/nifi/provenance_repository:Z
      - /srv/nifi/work:/opt/nifi/work:Z
      - /srv/nifi/logs:/opt/nifi/logs:Z
      - /tmp/data:/tmp/data:Z
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm137]
  nginx1:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - /root/nifi.cluster.docker.swarm/nginx1/:/etc/nginx/conf.d/:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm136]
  nginx2:
    image: "nginx"
    ports:
      - "85:85"
    volumes:
      - /root/nifi.cluster.docker.swarm/nginx2/:/etc/nginx/conf.d/:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm137]

  nifi3:
    image: mkobit/nifi:1.1.0-oracle-java8
    hostname: nifi3
    ports:
      - 8080:8080
    user: root
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    volumes:
      - /root/nifi.cluster.docker.swarm/nifi3/nifi.properties:/opt/nifi/conf/nifi.properties:ro
      - /root/nifi.cluster.docker.swarm/nifi3/bootstrap.conf:/opt/nifi/conf/bootstrap.conf:ro
      - /srv/nifi/flow:/opt/nifi/flow:Z
      - /srv/nifi/content_repository:/opt/nifi/content_repository:Z
      - /srv/nifi/database_repository:/opt/nifi/database_repository:Z
      - /srv/nifi/flowfile_repository:/opt/nifi/flowfile_repository:Z
      - /srv/nifi/provenance_repository:/opt/nifi/provenance_repository:Z
      - /srv/nifi/work:/opt/nifi/work:Z
      - /srv/nifi/logs:/opt/nifi/logs:Z
      - /tmp/data:/tmp/data:Z
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm138]
  nifi4:
    image: mkobit/nifi:1.1.0-oracle-java8
    hostname: nifi4
    ports:
      - 8085:8085
    user: root
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=7000,server=y,suspend=n
    volumes:
      - /root/nifi.cluster.docker.swarm/nifi4/nifi.properties:/opt/nifi/conf/nifi.properties:ro
      - /root/nifi.cluster.docker.swarm/nifi4/bootstrap.conf:/opt/nifi/conf/bootstrap.conf:ro
      - /srv/nifi/flow:/opt/nifi/flow:Z
      - /srv/nifi/content_repository:/opt/nifi/content_repository:Z
      - /srv/nifi/database_repository:/opt/nifi/database_repository:Z
      - /srv/nifi/flowfile_repository:/opt/nifi/flowfile_repository:Z
      - /srv/nifi/provenance_repository:/opt/nifi/provenance_repository:Z
      - /srv/nifi/work:/opt/nifi/work:Z
      - /srv/nifi/logs:/opt/nifi/logs:Z
      - /tmp/data:/tmp/data:Z
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm139]
  nginx3:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - /root/nifi.cluster.docker.swarm/nginx3/:/etc/nginx/conf.d/:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm138]
  nginx4:
    image: "nginx"
    ports:
      - "85:85"
    volumes:
      - /root/nifi.cluster.docker.swarm/nginx4/:/etc/nginx/conf.d/:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm139]
